### ISSUE TITLE
I can'nt arrive the paper's result?

### ISSUE THREAD

**Issue by ZFU123456** [lbktrinh/DRU#1]
The Batchsize=8, I use 4 4090GPU to train, when I set the first step:   sh configs/def-detr-base/city2foggy/source_only.sh, the results is: Best mAP50: 0.30, But when I set the second step: sh configs/def-detr-base/city2foggy/teaching_mask.sh, the result is Best mAP50: 0.40.
And during the 20th epoch, the test performance of the student model began to decline, followed by a decline in the test performance of the teacher model. Why is this happening?

**Comment by lbktrinh** [comment]
I guess you're having issues with DDP training. Have you tried using a single GPU? You can find more discussion in the link here: https://github.com/Lightning-AI/pytorch-lightning/discussions/3706

**Comment by FelixCaae** [comment]
I also encounterd this issue, did you solve this issue?
