### ISSUE TITLE
Number of classes in sim2city

### ISSUE THREAD

**Issue by krbism** [lbktrinh/DRU#2]
Dear Team,
Thank you for providing this wonderful work and its code. It is truly beautiful.

Can you please let me know why the sim2city configs set num_classes=4? Based on the eval, only one class i.e car is used and even the annotation of sim10k dataset contain only car so I was curious why was this chosen.
Will be waiting for your reply.

Thank you.

**Comment by lbktrinh** [comment]
The original SIM10k dataset includes 3 categories. Following previous work, we set the number of classes to 4, where index 0 represents non-objects. We here only detect cars, so setting class_num=2 should yield similar results.

**Comment by krbism** [comment]
Thanks.

**Comment by krbism** [comment]
On a side note, were you able to try the Kitty2Cityscapes setting too?

**Comment by lbktrinh** [comment]
I haven't tried it, but I think it will be similar to sim2city.
