### ISSUE TITLE
Clarification in the Evaluate function in engine.py

### ISSUE THREAD

**Issue by krbism** [lbktrinh/DRU#3]
https://github.com/lbktrinh/DRU/blob/a48fd752d66c1b972e9e675f5db1469c33bc8de2/engine.py#L381

Hi Team,
I notice that while getting pseudo labels from the evaluate function, the size of the thresholds is fixed as 9. In teaching functions the thresholds list is initialised in main.py as length of the number of classes. I'm trying this on adapting for a new setting where there are more than 9 classes and the source_only.py gave an error during evaluation as the length of the threshold list was getting mismatched.

**Comment by lbktrinh** [comment]
I don't understand your question much, but have you tried changing the number '9' to your number of classes?

**Comment by krbism** [comment]
Yes. we have tried. But I noticed that for datasets with less than 9 classes (eg. sim2city), the code still assumes number of classes to be 9. As the best weights are saved using the eval score mAP computed here, I was wondering if I have to rerun my experiments by changing 9 to 1 for sim2city.

**Comment by lbktrinh** [comment]
If you read the definition of get_pseudo_labels, keeping it as "9" doesn't affect sim2city.

**Comment by krbism** [comment]
Ok. Thank you for the clarification.
