### ISSUE TITLE
AP@50 What does it mean?

### ISSUE THREAD

**Issue by lqd666** [lbktrinh/DRU#4]
Evaluate only output in code AP@50 The results are accurate, but the comparative experiments in the paper seem to have maps ranging from 0.5 to 0.95. I would like to know why this is the case?

**Comment by lbktrinh** [comment]
Sorry, I don't understand your concern. Could you point out the specific experiments in the paper that seem to have maps ranging from 0.5 to 0.95? Thanks.

**Comment by lqd666** [comment]
> Sorry, I don't understand your concern. Could you point out the specific experiments in the paper that seem to have maps ranging from 0.5 to 0.95? Thanks.

Thanks for your reply
OH, maybe I translated it wrong. In the source code file readme. md, the fourth part of the experiment provides all models of this method. The accuracy achieved by this model is AP@50 As a benchmark, all comparative experiments in this article are based on AP@50 Is it a benchmark?For example, well-known methods such as LODS, IRG, TDD, etc., I thought the mAP achieved by these methods was all based on mAP@0.5:0.95 as the benchmark

**Comment by lbktrinh** [comment]
In the implementation details section of the LODS and IRG papers, the authors stated that AP@50 was used for testing.

**Comment by lqd666** [comment]
> In the implementation details section of the LODS and IRG papers, the authors stated that AP@50 was used for testing.
okay, thank you
